name: ML Model CI Training and Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install git and jq (system-wide)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git jq
        echo "Verifying git installation (system-wide):"
        /usr/bin/git --version
        echo "Verifying jq installation (system-wide):"
        jq --version

    - name: Set up Miniconda
      id: setup_conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.9' # Versi Python untuk base env Miniconda
        channels: conda-forge,defaults
        auto-activate-base: true # Default, memastikan base env aktif
        use-mamba: false

    - name: Install MLflow and GitPython in Conda base
      run: |
        echo "--- Verifying Conda Setup for MLflow Installation ---"
        echo "PATH: $PATH"
        echo "CONDA_PREFIX: $CONDA_PREFIX"
        echo "Which conda: $(which conda)"
        conda info --envs
        echo "Which python: $(which python)"
        python --version
        echo "Which pip: $(which pip)"
        pip --version
        echo "Installing MLflow (specific version) and GitPython using pip from active Conda env..."
        python -m pip install "mlflow>=2.0.0,<3.0.0" GitPython
        echo "Verifying MLflow version (running as module)..."
        python -m mlflow --version
        echo "Verifying GitPython version..."
        python -c "import git; print(f'GitPython version: {git.__version__}')"

    - name: Run MLflow Project and Capture Run ID
      id: mlflow_run_step
      env:
        GIT_PYTHON_GIT_EXECUTABLE: /usr/bin/git
        MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/MLProject_training/mlruns"
        EXPERIMENT_NAME_FOR_PYTHON: "CI Bitcoin Price Prediction"
      run: |
        echo "--- Verifying Environment for MLflow Run ---"
        echo "Current PATH: $PATH"
        echo "Which python: $(which python)"
        python --version
        
        echo "Running MLflow project for experiment: $EXPERIMENT_NAME_FOR_PYTHON"
        echo "MLFLOW_TRACKING_URI for run: $MLFLOW_TRACKING_URI"
        
        # Jalankan MLflow run seperti biasa
        python -m mlflow run MLProject_training/ --experiment-name "$EXPERIMENT_NAME_FOR_PYTHON"
        
        echo "Fetching latest Run ID using dedicated Python script..."
        # Memanggil skrip Python eksternal. 'python' di sini akan merujuk ke Python dari Conda base yang aktif.
        LATEST_RUN_ID=$(python scripts/get_latest_run_id.py)
        
        if [ $? -ne 0 ] || [ -z "$LATEST_RUN_ID" ] || [ "$LATEST_RUN_ID" == "null" ]; then
          echo "Bash script Error: Could not find latest Run ID using Python script (scripts/get_latest_run_id.py)."
          echo "Bash script LATEST_RUN_ID_content (if any): [$LATEST_RUN_ID]"
          exit 1
        fi
        echo "Latest Run ID is: $LATEST_RUN_ID"
        echo "run_id=$LATEST_RUN_ID" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      if: success() # Hanya jalankan jika langkah sebelumnya berhasil
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image using MLflow
      if: success() # Hanya jalankan jika langkah sebelumnya berhasil
      env:
        GIT_PYTHON_GIT_EXECUTABLE: /usr/bin/git
        MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/MLProject_training/mlruns"
      run: |
        RUN_ID="${{ steps.mlflow_run_step.outputs.run_id }}"
        if [ -z "$RUN_ID" ]; then
          echo "Error: Could not determine Run ID from previous step."
          exit 1
        fi
        echo "Using Run ID: $RUN_ID untuk membangun Docker image."
        
        MODEL_ARTIFACT_PATH="best-randomforest-model" 
        MODEL_URI="runs:/$RUN_ID/$MODEL_ARTIFACT_PATH"
        # Pastikan DOCKERHUB_USERNAME adalah username Anda di Docker Hub
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/bitcoin-price-predictor:latest" 
        
        echo "Model URI: $MODEL_URI"
        echo "Image Name: $IMAGE_NAME"

        echo "MLFLOW_TRACKING_URI for build-docker is set to: $MLFLOW_TRACKING_URI"
        
        # Menjalankan mlflow models build-docker sebagai modul Python
        python -m mlflow models build-docker \
          --model-uri "$MODEL_URI" \
          --name "$IMAGE_NAME" \
          --enable-mlserver

        echo "Pushing Docker image to Docker Hub..."
        docker push "$IMAGE_NAME"

    - name: Upload MLflow run artifacts
      if: always() # Selalu jalankan langkah ini, bahkan jika langkah sebelumnya gagal
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-run-artifacts
        path: MLProject_training/mlruns/ # Path relatif dari GITHUB_WORKSPACE
        retention-days: 7
