name: ML Model CI Training

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.9'
        channels: conda-forge,defaults
        use-mamba: false

    - name: Install system dependencies (git)
      run: |
        sudo apt-get update
        sudo apt-get install -y git # Memastikan git CLI terinstal di sistem runner

    - name: Install MLflow CLI (di base environment Conda)
      run: |
        echo "CONDA executable is at: $CONDA/bin/conda"
        echo "Installing MLflow in $CONDA/bin..."
        $CONDA/bin/pip install mlflow GitPython # Tambahkan GitPython di sini juga untuk jaga-jaga
        echo "MLflow version in Conda base:"
        $CONDA/bin/mlflow --version
        echo "GitPython version:"
        $CONDA/bin/python -c "import git; print(git.__version__)"


    - name: Run MLflow Project
      env:
        PATH: ${{ env.CONDA }}/bin:${{ env.PATH }}
        # Set variabel ini agar GitPython dapat menemukan git jika masih bermasalah
        # Namun, instalasi sistem git dan PATH yang benar seharusnya cukup
        # GIT_PYTHON_GIT_EXECUTABLE: /usr/bin/git # Path umum untuk git di Ubuntu
      run: |
        echo "--- Verifying Environment ---"
        echo "Current PATH: $PATH"
        echo "CONDA env variable: $CONDA"
        
        echo "Verifying git command..."
        git --version # Verifikasi git CLI sistem
        
        echo "Verifying conda command..."
        conda --version
        
        echo "Verifying mlflow command (from Conda base)..."
        mlflow --version
        
        echo "Running MLflow project..."
        mlflow run MLProject_training/ --experiment-name "CI Bitcoin Price Prediction"

    - name: Upload MLflow run artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-run-artifacts
        path: MLProject_training/mlruns/
        retention-days: 7
