name: ML Model CI Training and Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install git and jq (system-wide)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git jq # jq untuk parsing JSON
        echo "Verifying git installation (system-wide):"
        /usr/bin/git --version
        echo "Verifying jq installation (system-wide):"
        jq --version

    - name: Set up Miniconda
      id: setup_conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.9'
        channels: conda-forge,defaults
        use-mamba: false

    - name: Install MLflow CLI and GitPython (di base environment Conda)
      run: |
        echo "--- Verifying Conda Setup for MLflow Installation ---"
        echo "PATH: $PATH"
        echo "Which conda: $(which conda)"
        conda info --envs
        echo "Which python: $(which python)"
        python --version
        echo "Which pip: $(which pip)"
        pip --version
        echo "Installing MLflow and GitPython using pip from active Conda env..."
        python -m pip install mlflow GitPython
        echo "Verifying MLflow version (running as module)..."
        python -m mlflow --version
        echo "Verifying GitPython version..."
        python -c "import git; print(f'GitPython version: {git.__version__}')"

    - name: Run MLflow Project and Capture Run ID
      id: mlflow_run_step # Memberi ID pada langkah ini
      env:
        PATH: ${{ env.PATH }} # PATH dari sistem akan digabungkan dengan yang diset Conda
        GIT_PYTHON_GIT_EXECUTABLE: /usr/bin/git
      run: |
        echo "--- Verifying Environment for MLflow Run ---"
        echo "Current PATH: $PATH" # Akan menyertakan Conda base bin dari aktivasi
        echo "Which python: $(which python)"
        python --version
        
        EXPERIMENT_NAME_CI="CI Bitcoin Price Prediction" # Nama Eksperimen
        echo "Running MLflow project for experiment: $EXPERIMENT_NAME_CI"
        # Jalankan MLflow run
        # Output dari mlflow run akan otomatis masuk ke log, tidak perlu tee jika tidak ada parsing kompleks
        python -m mlflow run MLProject_training/ --experiment-name "$EXPERIMENT_NAME_CI"
        
        # Setelah mlflow run selesai, dapatkan run ID terbaru dari eksperimen tersebut
        echo "Fetching latest Run ID from experiment '$EXPERIMENT_NAME_CI'..."
        # Menggunakan mlflow runs list dengan --experiment-name dan mengambil run_id dari entri pertama (terbaru)
        LATEST_RUN_ID=$(python -m mlflow runs list --experiment-name "$EXPERIMENT_NAME_CI" --output-format json | jq -r '.[0].info.run_id')
        
        if [ -z "$LATEST_RUN_ID" ] || [ "$LATEST_RUN_ID" == "null" ]; then
          echo "Error: Could not find latest Run ID for experiment '$EXPERIMENT_NAME_CI'. Listing experiments and runs:"
          echo "Experiments:"
          python -m mlflow experiments list
          echo "Runs in default experiment:"
          python -m mlflow runs list --experiment-id 0 # Cek default experiment (ID 0)
          exit 1
        fi
        echo "Latest Run ID is: $LATEST_RUN_ID"
        echo "run_id=$LATEST_RUN_ID" >> $GITHUB_OUTPUT # Menyimpan Run ID sebagai output langkah

    - name: Log in to Docker Hub
      if: success()
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image using MLflow
      if: success()
      env:
        # PATH akan diwarisi, python dan mlflow (sebagai modul) seharusnya tersedia
        GIT_PYTHON_GIT_EXECUTABLE: /usr/bin/git
      run: |
        RUN_ID="${{ steps.mlflow_run_step.outputs.run_id }}"
        if [ -z "$RUN_ID" ]; then
          echo "Error: Could not determine Run ID from previous step."
          exit 1
        fi
        echo "Using Run ID: $RUN_ID untuk membangun Docker image."
        
        MODEL_ARTIFACT_PATH="best-randomforest-model" 
        MODEL_URI="runs:/$RUN_ID/$MODEL_ARTIFACT_PATH"
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/bitcoin-price-predictor:latest" 
        
        echo "Model URI: $MODEL_URI"
        echo "Image Name: $IMAGE_NAME"

        export MLFLOW_TRACKING_URI="file://$(pwd)/MLProject_training/mlruns"
        echo "MLFLOW_TRACKING_URI is set to: $MLFLOW_TRACKING_URI"
        
        python -m mlflow models build-docker \
          --model-uri "$MODEL_URI" \
          --name "$IMAGE_NAME" \
          --enable-mlserver

        echo "Pushing Docker image to Docker Hub..."
        docker push "$IMAGE_NAME"

    - name: Upload MLflow run artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-run-artifacts
        path: MLProject_training/mlruns/
        retention-days: 7
