name: ML Model CI Training

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    defaults:
      run:
        # Menggunakan shell bash dan memastikan login environment (-l) untuk memuat profil
        # yang mungkin mengatur PATH dengan benar. -e membuat skrip keluar jika ada error.
        shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install git (system-wide)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git
        echo "Verifying git installation (system-wide):"
        which git
        git --version

    # setup-python mungkin tidak diperlukan jika kita hanya akan menggunakan Python dari Conda
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.9'

    - name: Set up Miniconda
      id: setup_conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.9' # Versi Python untuk base env Miniconda
        channels: conda-forge,defaults # Pastikan ini sesuai dengan conda.yaml Anda
        # activate-environment: myenv # Jika Anda ingin mengaktifkan env tertentu yang dibuat di sini
        # architecture: x64 # Defaultnya adalah x64
        # auto-activate-base: false # Defaultnya true, yang berarti base env aktif
        use-mamba: false

    - name: Verify Conda environment and Install MLflow & GitPython
      run: |
        echo "--- Verifying Conda Setup ---"
        echo "CONDA_PREFIX: $CONDA_PREFIX" # Ini adalah path ke env Conda yang aktif (seharusnya base)
        echo "PATH: $PATH"
        echo "Which conda: $(which conda)"
        conda info
        
        echo "Which python: $(which python)"
        python --version
        
        echo "Which pip: $(which pip)"
        pip --version

        echo "Installing MLflow and GitPython using pip from active Conda env..."
        pip install mlflow GitPython
        
        echo "Verifying MLflow version (running as module)..."
        python -m mlflow --version
        
        echo "Verifying GitPython version..."
        python -c "import git; print(f'GitPython version: {git.__version__}')"

    - name: Run MLflow Project
      env:
        GIT_PYTHON_GIT_EXECUTABLE: /usr/bin/git # Path absolut ke git sistem
        # PATH akan diwarisi dari langkah sebelumnya, di mana Conda base aktif
      run: |
        echo "--- Verifying Environment for MLflow Run ---"
        echo "Current PATH: $PATH"
        echo "Which python: $(which python)"
        python --version
        echo "Which mlflow: $(which mlflow || echo 'mlflow CLI not directly in PATH, will run as module')"

        echo "Verifying system git command (using /usr/bin/git)..."
        /usr/bin/git --version
        
        echo "Verifying conda command (from PATH)..."
        conda --version
        
        echo "GIT_PYTHON_GIT_EXECUTABLE is set to: $GIT_PYTHON_GIT_EXECUTABLE"

        echo "Running MLflow project..."
        # Menjalankan mlflow run sebagai modul Python dari Conda base
        python -m mlflow run MLProject_training/ --experiment-name "CI Bitcoin Price Prediction"

    - name: Upload MLflow run artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-run-artifacts
        path: MLProject_training/mlruns/
        retention-days: 7
