name: ML Model CI Training and Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-build-docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install git and jq (system-wide)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git jq # Menambahkan jq untuk parsing JSON
        echo "Verifying git installation (system-wide):"
        /usr/bin/git --version
        echo "Verifying jq installation (system-wide):"
        jq --version

    - name: Set up Miniconda
      id: setup_conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.9' # Sesuaikan dengan versi Python di conda.yaml Anda
        channels: conda-forge,defaults
        use-mamba: false

    - name: Install MLflow CLI and GitPython (di base environment Conda)
      run: |
        echo "Python executable in Conda base is: ${{ steps.setup_conda.outputs.python-path }}"
        echo "Installing MLflow and GitPython in Conda base using pip..."
        ${{ steps.setup_conda.outputs.python-path }} -m pip install mlflow GitPython
        echo "Verifying MLflow version in Conda base..."
        ${{ steps.setup_conda.outputs.python-path }} -m mlflow --version
        echo "Verifying GitPython version in Conda base..."
        ${{ steps.setup_conda.outputs.python-path }} -c "import git; print(f'GitPython version: {git.__version__}')"

    - name: Run MLflow Project and Capture Run ID
      id: mlflow_run_step
      env:
        PATH: ${{ steps.setup_conda.outputs.conda-bin-path }}:${{ env.PATH }}
        GIT_PYTHON_GIT_EXECUTABLE: /usr/bin/git # Path absolut ke git sistem
      run: |
        echo "--- Verifying Environment for MLflow Run ---"
        /usr/bin/git --version
        conda --version
        ${{ steps.setup_conda.outputs.python-path }} -m mlflow --version
        
        EXPERIMENT_NAME_CI="CI Bitcoin Price Prediction" # Nama Eksperimen
        echo "Running MLflow project for experiment: $EXPERIMENT_NAME_CI"
        # Jalankan MLflow run
        ${{ steps.setup_conda.outputs.python-path }} -m mlflow run MLProject_training/ --experiment-name "$EXPERIMENT_NAME_CI"
        
        # Setelah mlflow run selesai, dapatkan experiment ID
        echo "Fetching Experiment ID for '$EXPERIMENT_NAME_CI'..."
        EXPERIMENT_ID=$(${{ steps.setup_conda.outputs.python-path }} -m mlflow experiments list --query "name='$EXPERIMENT_NAME_CI'" --output-format json | jq -r '.[0].experiment_id')
        if [ -z "$EXPERIMENT_ID" ] || [ "$EXPERIMENT_ID" == "null" ]; then
          echo "Error: Could not find Experiment ID for '$EXPERIMENT_NAME_CI'. Listing all experiments:"
          ${{ steps.setup_conda.outputs.python-path }} -m mlflow experiments list
          exit 1
        fi
        echo "Experiment ID for '$EXPERIMENT_NAME_CI' is: $EXPERIMENT_ID"
        
        # Dapatkan run ID terbaru dari eksperimen tersebut
        echo "Fetching latest Run ID from Experiment ID $EXPERIMENT_ID..."
        LATEST_RUN_ID=$(${{ steps.setup_conda.outputs.python-path }} -m mlflow runs list --experiment-id "$EXPERIMENT_ID" --output-format json | jq -r '.[0].run_id')
        if [ -z "$LATEST_RUN_ID" ] || [ "$LATEST_RUN_ID" == "null" ]; then
          echo "Error: Could not find latest Run ID for Experiment ID $EXPERIMENT_ID. Listing runs:"
          ${{ steps.setup_conda.outputs.python-path }} -m mlflow runs list --experiment-id "$EXPERIMENT_ID"
          exit 1
        fi
        echo "Latest Run ID is: $LATEST_RUN_ID"
        echo "run_id=$LATEST_RUN_ID" >> $GITHUB_OUTPUT # Menyimpan Run ID sebagai output langkah

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image using MLflow
      env:
        PATH: ${{ steps.setup_conda.outputs.conda-bin-path }}:${{ env.PATH }}
        # MLFLOW_TRACKING_URI akan diset di dalam run command
      run: |
        RUN_ID="${{ steps.mlflow_run_step.outputs.run_id }}"
        if [ -z "$RUN_ID" ]; then
          echo "Error: Could not determine Run ID from previous step."
          exit 1
        fi
        echo "Using Run ID: $RUN_ID untuk membangun Docker image."
        
        # Sesuaikan 'best-randomforest-model' jika nama artefak model Anda berbeda di skrip modelling.py
        MODEL_ARTIFACT_PATH="best-randomforest-model" 
        MODEL_URI="runs:/$RUN_ID/$MODEL_ARTIFACT_PATH"
        # Menggunakan username Anda dari secret dan nama image yang Anda inginkan
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/bitcoin-price-predictor:latest" 
        
        echo "Model URI: $MODEL_URI"
        echo "Image Name: $IMAGE_NAME"

        # Set MLFLOW_TRACKING_URI agar mlflow models tahu di mana mencari run lokal
        # $(pwd) akan menjadi root dari GITHUB_WORKSPACE
        export MLFLOW_TRACKING_URI="file://$(pwd)/MLProject_training/mlruns"
        echo "MLFLOW_TRACKING_URI is set to: $MLFLOW_TRACKING_URI"
        
        ${{ steps.setup_conda.outputs.python-path }} -m mlflow models build-docker \
          --model-uri "$MODEL_URI" \
          --name "$IMAGE_NAME" \
          --enable-mlserver # Menggunakan MLServer untuk serving (opsional)

        echo "Pushing Docker image to Docker Hub..."
        docker push "$IMAGE_NAME"

    - name: Upload MLflow run artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-run-artifacts
        path: MLProject_training/mlruns/
        retention-days: 7
