name: ML Model CI Training

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install git (system-wide)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git
        echo "Verifying git installation (system-wide):"
        ls -l /usr/bin/git # Cek keberadaan file
        /usr/bin/git --version # Panggil dengan path absolut

    - name: Set up Python (untuk runner jika diperlukan sebelum Conda)
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.9' # Ini versi Python untuk base env Miniconda
        channels: conda-forge,defaults
        use-mamba: false

    - name: Install MLflow CLI and GitPython (di base environment Conda)
      run: |
        echo "CONDA executable is at: $CONDA/bin/conda"
        echo "Installing MLflow and GitPython in $CONDA/bin..."
        # Pastikan pip menggunakan versi python yang benar
        $CONDA/bin/python -m pip install mlflow GitPython
        echo "MLflow version in Conda base:"
        $CONDA/bin/mlflow --version
        echo "GitPython version in Conda base:"
        $CONDA/bin/python -c "import git; print(git.__version__)"

    - name: Run MLflow Project
      env:
        # Pastikan /usr/bin ada di PATH yang dilihat oleh semua proses
        # $CONDA/bin juga penting untuk mlflow CLI itu sendiri
        PATH: /usr/bin:${CONDA}/bin:${PATH}
        GIT_PYTHON_GIT_EXECUTABLE: /usr/bin/git # Set secara eksplisit
        # MLFLOW_CONDA_HOME: ${{ env.CONDA }} # Biasanya otomatis terdeteksi
      run: |
        echo "--- Verifying Environment ---"
        echo "Current PATH: $PATH"
        echo "CONDA env variable: $CONDA"
        
        echo "Verifying system git command (using /usr/bin/git)..."
        /usr/bin/git --version
        
        echo "Verifying conda command..."
        conda --version
        
        echo "Verifying mlflow command (from Conda base)..."
        mlflow --version
        
        echo "GIT_PYTHON_GIT_EXECUTABLE is set to: $GIT_PYTHON_GIT_EXECUTABLE"

        echo "Running MLflow project..."
        # MLflow akan membuat environment baru berdasarkan conda.yaml (mlflow-xxxx)
        # GitPython akan dijalankan di dalam environment tersebut.
        mlflow run MLProject_training/ --experiment-name "CI Bitcoin Price Prediction"

    - name: Upload MLflow run artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-run-artifacts
        path: MLProject_training/mlruns/
        retention-days: 7
